name: Publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - .vscode/**
      - LICENSE
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Prepare
        run: |-
          sudo timedatectl set-timezone Asia/Shanghai
          yarn
      - name: Build
        run: |-
          yarn build
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm version $VERSION_OPTS
          npm publish $PUBLISH_OPTS
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          VERSION_OPTS: ${{ github.ref_name == 'main' && 'minor' || 'patch' }}
          PUBLISH_OPTS: ${{ github.ref_name == 'main' && '' || '--tag=next' }}
